nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': 
            allow_origin: ['http://localhost:3000'] # set the allowed origin
            allow_headers: ['Content-Type', 'Authorization'] # set the allowed headers
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH'] # set the allowed HTTP methods
            max_age: 3600 # set the maximum age for preflight requests (in seconds)
